### ISSUE TITLE
How to set up on my own server?

### ISSUE THREAD

**Issue by georgkaser** [jacany/nblog#1]
Hi, I want to set it up on my Ubuntu Server - can you give me a "howto"?

**Comment by jacany** [comment]
Hello,
Yes. I apologize for the lack of documentation in the readme.
You're going to want to ensure that you have nodejs installed. If not look into downloading nvm (node version manager)
Once you get node setup, you're going to want to fork this repository. Then git clone it to your server.
after you've cloned it, run `yarn`. This will install all of the required packages.
configure it by adding a `.env` file in the root directory of the project. See the configuration section of README.md
after you've configured it.
run `yarn build`, and then `yarn preview`. This will build and then run the server.

I will look into writing better documentation for those not using vercel.

**Comment by georgkaser** [comment]
Fantastic! Thank you, it works. How to add some content now?

**Comment by jacany** [comment]
Post from a client like https://habla.news and the post will appearSent from my iPhoneOn Apr 4, 2023, at 3:46 PM, Georg Kaser ***@***.***> wrote:﻿
Fantastic! Thank you, it works. How to add some content now?
