### ISSUE TITLE
vercel bug - 

### ISSUE THREAD

**Issue by rabble** [jacany/nblog#4]
I deployed to vercel and it worked when there were not blog posts, but when i did my first test post i get this error:

> TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
>     at getTagValues (file:///var/task/.svelte-kit/output/server/chunks/util.js:7:32)
>     at file:///var/task/.svelte-kit/output/server/chunks/ListPost.js:11:17
>     at Object.$$render (file:///var/task/.svelte-kit/output/server/chunks/index3.js:113:18)
>     at file:///var/task/.svelte-kit/output/server/entries/pages/posts/_page.svelte.js:11:74
>     at each (file:///var/task/.svelte-kit/output/server/chunks/index3.js:84:12)
>     at file:///var/task/.svelte-kit/output/server/entries/pages/posts/_page.svelte.js:10:22
>     at Object.$$render (file:///var/task/.svelte-kit/output/server/chunks/index3.js:113:18)
>     at Object.default (file:///var/task/.svelte-kit/output/server/chunks/internal.js:69:98)
>     at file:///var/task/.svelte-kit/output/server/entries/pages/_layout.svelte.js:19:84
>     at Object.$$render (file:///var/task/.svelte-kit/output/server/chunks/index3.js:113:18)

**Comment by jacany** [comment]
Hello,
If you could provide your enviroment variables that would greatly help with assisting in this problem.

Sent from my iPhone

On Apr 7, 2023, at 7:48 PM, rabble ***@***.***> wrote:

﻿

I deployed to vercel and it worked when there were not blog posts, but when i did my first test post i get this error:

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
at getTagValues (file:///var/task/.svelte-kit/output/server/chunks/util.js:7:32)
at file:///var/task/.svelte-kit/output/server/chunks/ListPost.js:11:17
at Object.$$render (file:///var/task/.svelte-kit/output/server/chunks/index3.js:113:18)
at file:///var/task/.svelte-kit/output/server/entries/pages/posts/_page.svelte.js:11:74
at each (file:///var/task/.svelte-kit/output/server/chunks/index3.js:84:12)
at file:///var/task/.svelte-kit/output/server/entries/pages/posts/_page.svelte.js:10:22
at Object.$$render (file:///var/task/.svelte-kit/output/server/chunks/index3.js:113:18)
at Object.default (file:///var/task/.svelte-kit/output/server/chunks/internal.js:69:98)
at file:///var/task/.svelte-kit/output/server/entries/pages/_layout.svelte.js:19:84
at Object.$$render (file:///var/task/.svelte-kit/output/server/chunks/index3.js:113:18)

**Comment by jacany** [comment]
Actually, completely disregard what I said. It seems like one of your posts doesn't have a summary field. For a comvienent, temporary fix please add one while I squash this bug.

**Comment by jacany** [comment]
Thanks, I'll look into it.
What clients are you using to post, how many posts do you have, and if you do have posts make sure they have a summary attached.

**Comment by jacany** [comment]
Fixed in c09377d
