### ISSUE TITLE
Link button doesn't do anything

### ISSUE THREAD

**Issue by staab** [jacany/nblog#5]
The permalink button by a post title doesn't seem to do anything. It would also be helpful to be able to click the post title on the home page to get a permalink.

**Comment by jacany** [comment]
> The permalink button by a post title doesn't seem to do anything.

What browser are you using?

**Comment by staab** [comment]
Brave, just looked into it more closely and it looks like clicking it copies the link to the clipboard, but there's no indication that's what has happened, so it's more of a UI thing than a bug. And to clarify, the post I'm referring to is the post title for the first post on the homepage.

**Comment by jacany** [comment]
Resolved in 14d9370 and 90c5853
